#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Rotate the Portfolio Discord webhook (issue #29)"

# ── Stage 1: scope the incident ────────────────────────────────────────────
stage "What this fixes, and what it doesn't touch"
say "The contact form's Discord webhook shipped in a public GitHub Pages"
say "bundle for roughly two years before the contact form moved server-side."
say "Anyone who captured that URL during that window can still post to the"
say "channel directly today, bypassing every server-side control (rate"
say "limit, honeypot, field caps). Rotating it at Discord is what actually"
say "closes that -- editing files does not un-publish a credential that"
say "already shipped."
say ""
say "Where the credential lives right now:"
step "Render service 'portfolio-api', env var WEBHOOK_URL (dashboard-only,"
say "  not in any file -- this is the one the running backend reads)."
step "An orphaned GitHub Actions repo secret named DISCORD_WEBHOOK, unused"
say "  by any current workflow, almost certainly holding the same stale"
say "  value. Stage 7 removes it."
say ""
warn "This wizard never asks you to paste the webhook URL, old or new, into"
warn "this terminal. Every value below goes directly into Discord's or"
warn "Render's own UI, never through this script."
pause "Ready to start?"

# ── Stage 2: revoke the old webhook at Discord ─────────────────────────────
stage "Discord: revoke the old webhook"
say "This is the actual fix. Nothing else in this wizard matters until this"
say "step is done -- the old URL stays live against Discord's API until you"
say "delete it here, no matter what changes on Render or in the repo."
open_url "https://discord.com/app"
step "Open the server that owns the contact-form channel."
step "Channel settings (or Server Settings) -> Integrations -> Webhooks."
step "Find the webhook backing the contact form."
step "Delete it. Confirm the deletion."
note "Discord invalidates the URL immediately -- no propagation delay."
confirm "Old webhook deleted in Discord?" || warn "stopping here -- rerun this wizard once it's deleted"

# ── Stage 3: create the replacement webhook ────────────────────────────────
stage "Discord: create the replacement"
say "Same channel, same server, brand new webhook."
step "Integrations -> Webhooks -> New Webhook (or Create Webhook)."
step "Name it however you name the others, then copy its URL."
warn "Keep that URL in your clipboard or a password manager only. Do not"
warn "paste it into this terminal, a file, chat, or anywhere it could be"
warn "logged -- that is the exact mechanism that exposed the last one."
confirm "New webhook created and its URL copied somewhere private?" || warn "stopping here -- rerun once done"

# ── Stage 4: point Render at the new webhook ───────────────────────────────
stage "Render: set WEBHOOK_URL on portfolio-api"
say "render.yaml marks WEBHOOK_URL as sync: false on purpose -- it is set by"
say "hand in the dashboard, never committed. That's where you paste the new"
say "URL, not here."
open_url "https://dashboard.render.com/"
step "Open the portfolio-api service -> Environment."
step "Edit WEBHOOK_URL, paste the new webhook URL from your clipboard,"
say "  save."
step "Trigger a manual deploy if Render doesn't redeploy automatically on"
say "  an environment change (check the service's deploy history)."
confirm "WEBHOOK_URL updated on Render and the service redeployed?" || warn "stopping here -- rerun once done"

# ── Stage 5: verify the new webhook actually works ─────────────────────────
stage "Verify: submit a real test message"
open_url "https://alcash55.github.io/Portfolio/"
step "Fill out the live contact form with a throwaway test message."
step "Submit it."
step "Check the Discord channel: the message should land there via the new"
say "  webhook."
confirm "Test message arrived in Discord?" || warn "if it didn't, re-check the WEBHOOK_URL value on Render before continuing"

# ── Stage 6: confirm the old webhook is actually dead ──────────────────────
stage "Verify: the old webhook is dead"
say "Run this yourself, directly in your own shell -- not through this"
say "wizard -- with the OLD webhook URL substituted in by hand:"
say ""
say '  curl -i -X POST -H "Content-Type: application/json" \'
say '    -d '"'"'{"content":"rotation check"}'"'"' \'
say '    "<paste the OLD webhook URL here, then clear it from your shell history>"'
say ""
note "A deleted Discord webhook returns 401 Unauthorized or 404 Not Found."
note "200 here means Stage 2 didn't take -- go back and delete it at Discord."
confirm "Old webhook confirmed dead (401/404)?" || warn "go back to Stage 2 before continuing"

# ── Stage 7: remove the orphaned GitHub Actions secret ─────────────────────
stage "GitHub: delete the orphaned DISCORD_WEBHOOK secret"
say "This secret predates the Go backend, is unused by every current"
say "workflow (deploy.yml's own DISCORD_WEBHOOK_URL is a separate, currently"
say "unset slot for CI deploy-outcome notifications -- do not confuse the"
say "two or reuse one for the other), and almost certainly holds the same"
say "stale value you just revoked. An unused secret holding a live"
say "credential is its own risk, so it goes now rather than later."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Delete the GitHub Actions secret DISCORD_WEBHOOK now via gh?"; then
    if gh secret delete DISCORD_WEBHOOK >/dev/null 2>&1; then
      printf '  %s✓ deleted%s GitHub secret DISCORD_WEBHOOK\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("GitHub secret DISCORD_WEBHOOK (gh secret delete failed -- remove it by hand)")
      warn "gh secret delete failed -- remove it by hand (see below)"
    fi
  else
    SKIPPED+=("GitHub secret DISCORD_WEBHOOK (delete by hand)")
  fi
else
  open_url "https://github.com/alcash55/Portfolio/settings/secrets/actions"
  step "Find DISCORD_WEBHOOK in the list and delete it."
  SKIPPED+=("GitHub secret DISCORD_WEBHOOK (gh not ready -- delete it by hand)")
fi

finish
say "Checklist: old webhook dead, new webhook live in Render's WEBHOOK_URL"
say "only, orphaned GitHub secret gone. If any of those isn't true yet,"
say "rerun this wizard from that stage."
