name: Check Resume

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'frontend/src/assets/AlexResume.pdf'

jobs:
  check-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ATS Check
        id: ats_check
        uses: alcash55/ac-composite-actions/ats-check@main
        with:
          RESUME: ./frontend/src/assets/AlexResume.pdf
          APILAYER_API_KEY: ${{ secrets.APILAYER_API_KEY }}

      - name: Output ATS Check Results
        run: |
          echo "ATS Check Report: ${{ steps.ats_check.outputs.ATS_REPORT }}"
          echo "ATS Check Score: ${{ steps.ats_check.outputs.ATS_SCORE }}"
          echo "ATS Check Passed: ${{ steps.ats_check.outputs.ATS_PASSED }}"
