name: Check Resume

on:
  workflow_dispatch:

jobs:
  check-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: ATS Check
        id: ats_check
        uses: alcash55/ac-composite-actions/ats-check@main
        with:
          RESUME: ./src/assets/AlexResume.pdf

      - name: Output ATS Check Results
        run: |
          echo "ATS Check Report: ${{ steps.ats_check.outputs.ATS_REPORT }}"
          echo "ATS Check Score: ${{ steps.ats_check.outputs.ATS_SCORE }}"
          echo "ATS Check Passed: ${{ steps.ats_check.outputs.ATS_PASSED }}"
